version: "3.9"

services:

  api:
    build: .
    command: uv run uvicorn ui.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  streamlit:
    build: .
    command: uv run streamlit run ui/prediction_ui.py --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api