name: Python CI with Poetry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry --version

      - name: Install dependencies
        run: poetry install

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run Black (code formatting)
        run: poetry run black --line-length 79 .

      - name: Run experiments and train models
        run: poetry run python run.py

      - name: Register best model
        run: poetry run python california_houseprice_prediction/domain/register_model.py

      - name: Start API in background
        run: |
          poetry run uvicorn california_houseprice_prediction.application.api:app --host 0.0.0.0 --port 8000 &
          echo "API started on port 8000"

      - name: Run tests
        run: poetry run pytest tests/ -v

      - name: Test MLflow serving
        run: |
          # Démarrer le serveur MLflow sans créer un nouvel environnement
          poetry run mlflow models serve -m models:/sk-learn-gradient-boosting-reg@champion -p 5001 --no-conda &
          sleep 10  # Attendre que le serveur démarre

          # Tester le modèle avec une requête
          poetry run python test_mlflow_serving.py

      - name: Notify Slack on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "CI/CD pipeline failed :x:"